
void function() {
    __leave; // expected-error{{'__leave' statement not in __try block}}
}
